using System;
using System.Windows;

namespace VacuumBreather.Mvvm.Wpf;

/// <summary>
///     If a view-model class is marked with this attribute, no <see cref="DataTemplate" /> based on its corresponding view
///     type will be auto-generated.
/// </summary>
/// <seealso cref="System.Attribute" />
[AttributeUsage(AttributeTargets.Class, Inherited = false)]
public sealed class NoAutoGeneratedDataTemplateAttribute : Attribute
{
}